
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FALSE ID LP PATIENT PERIOD RP TRUE program : function\n                | create_patient\n                | add_symptoms\n                | list_symptoms\n                | diagnose_patient \n                | specific_diagnose\n                | create_illness\n                | add_conditions\n                \n                \n    function : ID\n    create_patient : ID PERIOD LP RPcreate_illness : ID LP ID RP PERIOD ID LP RPadd_conditions : ID LP ID RP PERIOD ID LP ID RP add_symptoms : ID PERIOD ID LP ID RP  list_symptoms : ID PERIOD ID LP RP diagnose_patient : ID PERIOD ID  specific_diagnose : ID PERIOD ID LP ID RP PERIOD ID LP RP'
    
_lr_action_items = {'ID':([0,11,12,16,21,24,25,],[10,13,15,19,23,26,27,]),'$end':([1,2,3,4,5,6,7,8,9,10,13,17,20,22,28,30,31,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-15,-10,-14,-13,-11,-12,-16,]),'PERIOD':([10,18,22,],[11,21,24,]),'LP':([10,11,13,23,26,],[12,14,16,25,29,]),'RP':([14,15,16,19,25,27,29,],[17,18,20,22,28,30,31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'function':([0,],[2,]),'create_patient':([0,],[3,]),'add_symptoms':([0,],[4,]),'list_symptoms':([0,],[5,]),'diagnose_patient':([0,],[6,]),'specific_diagnose':([0,],[7,]),'create_illness':([0,],[8,]),'add_conditions':([0,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> function','program',1,'p_program','care_parse.py',10),
  ('program -> create_patient','program',1,'p_program','care_parse.py',11),
  ('program -> add_symptoms','program',1,'p_program','care_parse.py',12),
  ('program -> list_symptoms','program',1,'p_program','care_parse.py',13),
  ('program -> diagnose_patient','program',1,'p_program','care_parse.py',14),
  ('program -> specific_diagnose','program',1,'p_program','care_parse.py',15),
  ('program -> create_illness','program',1,'p_program','care_parse.py',16),
  ('program -> add_conditions','program',1,'p_program','care_parse.py',17),
  ('function -> ID','function',1,'p_function','care_parse.py',23),
  ('create_patient -> ID PERIOD LP RP','create_patient',4,'p_create_patient','care_parse.py',32),
  ('create_illness -> ID LP ID RP PERIOD ID LP RP','create_illness',8,'p_create_illness','care_parse.py',38),
  ('add_conditions -> ID LP ID RP PERIOD ID LP ID RP','add_conditions',9,'p_add_conditions','care_parse.py',44),
  ('add_symptoms -> ID PERIOD ID LP ID RP','add_symptoms',6,'p_add_symptoms','care_parse.py',50),
  ('list_symptoms -> ID PERIOD ID LP RP','list_symptoms',5,'p_list_symptoms','care_parse.py',56),
  ('diagnose_patient -> ID PERIOD ID','diagnose_patient',3,'p_diagnose_patient','care_parse.py',68),
  ('specific_diagnose -> ID PERIOD ID LP ID RP PERIOD ID LP RP','specific_diagnose',10,'p_specific_diagnose','care_parse.py',74),
]
